Bug 90707, 91759, 91954, 91955: Wallet bugs and enhancements from UAT #2
BenGWeeks/Zapp.ie pull request #38
Opened 2024-10-04 15:43 UTC by akash2017sky

This PR fixes the following bugs & enhancements:

- [Enhancement 90707](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/90707): Modify allowance screen to get the weekly allowance from LNbits using the extension for allowance
- [Bug 91759](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/91759): Buy button is broken
- [Bug 91954](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/91954): Allowance should show "Sent to" from "received from"
- [Enhancement 90707](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/90707): Modify allowance screen to get the weekly allowance from LNbits using the extension for allowance

In addition:

- Removed some `console.log()`
- Removed unneeded imports

@EdiWeeks, to test this, please run (in a `bash` terminal):

```bash
cd tabs
rm -rf node_modules
npm install
npm start
```

2024-10-05 14:41 UTC, BenGWeeks requested changes
Please get in the habit of giving good, insightful descriptions to your PRs if you want them reviewed (have updated it with what I expect) :-)

2024-10-05 14:41 UTC, BenGWeeks commented on tabs/src/services/lnbitsServiceLocal.ts
> -const getAllowance = async (
This should be left in here, since it will be a call to LNbits.

2024-10-05 14:41 UTC, BenGWeeks commented on tabs/src/services/userService.ts
> +const getAllowance = async (
Put back into LNBits service, since will be calling LNbits endpoint to get it.

2024-10-05 14:41 UTC, BenGWeeks commented on tabs/src/services/userService.ts
> +export { getCurrentUser, getAllUsers, getFriends, getAllowance, };
Remove `getAllowance` from here

2024-10-05 17:52 UTC, BenGWeeks commented
- [Bug 91955](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/91955): Spent this week to match transactions
- Implemented changes requested in review
- Renamed `user` to `users` to be clear when it is an array

2024-10-21 11:12 UTC, EdiWeeks commented
@akash2017sky Please can you resolve conflict. I am not seeing several changes we made in Test environment.

2024-10-22 12:48 UTC, BenGWeeks commented on .github/workflows/UAT-release.yml
Do you mean "Test"? Let's be consistent with the naming of these workflows and to be clear it's just the react web app. See Alice.

2024-10-22 12:48 UTC, BenGWeeks commented on appPackage/manifest.json
> +            "contentUrl": "https://localhost:3000",
Is this correct?

2024-10-23 09:07 UTC, EdiWeeks commented
@akash2017sky please can you resolve conflict here then tag me as I need to test this again.

2024-10-24 11:48 UTC, BenGWeeks commented on tabs/src/components/SignOutButton.tsx
OK to merge these changes for now I presume until pop-up redirect merged in @desousamario85 ?

2024-12-06 09:42 UTC, BenGWeeks commented
Comments and merge conflict pending @akash2017sky

2025-01-08 17:07 UTC, EdiWeeks approved these changes
Tested

2025-01-13 09:30 UTC, BenGWeeks commented
This seems to have a bunch of updates to do with performance? But you have a separate PR for that?! @akash2017sky / @EdiWeeks

2025-01-28 09:48 UTC, EdiWeeks commented
Conflict has been resolved.

2025-01-28 16:28 UTC, BenGWeeks commented
New conflict @akash2017sky ?

2025-01-30 22:12 UTC, BenGWeeks commented
Comment in teams to close.

Keep your PRs separate please @akash2017sky

2025-01-30 22:12 UTC, closed without merging